# Generated by Django 5.0.4 on 2024-05-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_secret',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
