# Generated by Django 5.0.4 on 2024-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workplans', '0002_customuser_verification_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_secret',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
