# Generated by Django 5.0.4 on 2024-05-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workplans', '0004_workplans_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workplans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workplans.workplans'),
        ),
    ]
